#!/usr/bin/env python3
"""Re-verify every C version in c/history/ and every Python version in python/.

For each C file: character count, gcc warning count, compile time, binary size,
TREE(1) and TREE(2) results (with AddressSanitizer + UBSan), and a short TREE(3) run
(timeout = still searching, which is the expected outcome).
Writes logs/history_results.md, logs/history_results.csv and per-file logs in logs/c/.
"""
import csv, os, re, subprocess, sys, time, glob
ROOT=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
os.makedirs('logs/c',exist_ok=True); os.makedirs('logs/python',exist_ok=True)
T3=int(os.environ.get('TREE3_SECONDS','3'))
# Memory leaks are expected (the golfed code never frees); leak reports are not correctness failures.
os.environ['ASAN_OPTIONS']='detect_leaks=0'

def run(cmd,timeout=None,inp=None):
    t=time.time()
    try:
        p=subprocess.run(cmd,capture_output=True,text=True,timeout=timeout,input=inp)
        return p.returncode,p.stdout,p.stderr,time.time()-t
    except subprocess.TimeoutExpired as e:
        return 'timeout',(e.stdout or b'').decode() if isinstance(e.stdout,bytes) else (e.stdout or ''),'',time.time()-t

def colour_variant(src,n):
    """Return a source computing TREE(n) instead of TREE(3), or None if it takes argv."""
    if 'atoi' in src: return None
    s=src
    if '3*v' in s: s=s.replace('3*v',f'{n}*v').replace('c/3',f'c/{n}').replace('c%3',f'c%{n}')
    else: s=s.replace('c=3;',f'c={n};').replace('p<3;',f'p<{n};')
    return s

rows=[]
for f in sorted(glob.glob('c/history/*.c')):
    name=os.path.basename(f); src=open(f).read()
    chars=len(src.replace('\n',''))
    log=[f'# {name}', f'chars (no line breaks): {chars}', '']
    rc,_,err,ct=run(['gcc','-Wall','-Wextra','-o','/tmp/vb',f])
    warns=len(re.findall(r'warning:',err)); errs=len(re.findall(r'error:',err))
    size=os.path.getsize('/tmp/vb') if rc==0 else 0
    log+=[f'## gcc -Wall -Wextra (rc={rc}, {ct:.2f}s, {warns} warnings, {errs} errors, binary {size} bytes)','```',err.strip()[:20000],'```','']
    res={}
    for n in (1,2):
        v=colour_variant(src,n)
        if v is None: srcf=f; args=[str(n)]
        else:
            srcf=f'/tmp/v{n}.c'; open(srcf,'w').write(v); args=[]
        rc2,_,e2,_=run(['gcc','-w','-g','-fsanitize=address,undefined','-o',f'/tmp/va{n}',srcf])
        r,out,e,dt=run([f'/tmp/va{n}']+args,timeout=120)
        res[n]=(out.strip().splitlines() or ['?'])[-1][:20] if r==0 else f'rc={r}'
        san='ERROR' if ('ERROR: AddressSanitizer' in e or 'runtime error' in e) else 'clean'
        log+=[f'## TREE({n}) under ASan/UBSan: output={res[n]!r} rc={r} time={dt:.2f}s sanitizers={san}']
        if san!='clean': log+=['```',e[:4000],'```']
    srcf=f; args=['3'] if 'atoi' in src else []
    r,out,e,dt=run(['/tmp/vb']+args,timeout=T3)
    t3='still searching (expected)' if r=='timeout' else f'exited rc={r} out={out.strip()[:20]!r}'
    log+=[f'## TREE(3) for {T3}s: {t3}','']
    ok=res[1]=='1' and res[2]=='3' and r=='timeout'
    log+=[f'**Result: {"PASS" if ok else "FAIL"}**']
    open(f'logs/c/{name}.md','w').write('\n'.join(log)+'\n')
    rows.append(dict(file=name,chars=chars,warnings=warns,compile_s=f'{ct:.2f}',binary_bytes=size,tree1=res[1],tree2=res[2],tree3=t3,result='PASS' if ok else 'FAIL'))
    print(name,chars,res,t3,'PASS' if ok else 'FAIL',flush=True)

prow=[]
for f in sorted(glob.glob('python/[0-9]*.py')):
    src=open(f).read(); name=os.path.basename(f)
    v=re.sub(r'r=0,1,2\b','r=0,1',src) if 'r=0,1,2' in src else None
    if v is None:
        prow.append(dict(file=name,bytes=len(src),tree2='not tested (colour set not parameterised)')); continue
    open('/tmp/p2.py','w').write(v)
    r,out,e,dt=run([sys.executable,'/tmp/p2.py'],timeout=120)
    t2=out.strip() if r==0 else f'rc={r}'
    open(f'logs/python/{name}.log','w').write(f'TREE(2) run: rc={r} time={dt:.2f}s\nstdout: {out}\nstderr: {e[-2000:]}\n')
    prow.append(dict(file=name,bytes=len(src),tree2=t2)); print(name,t2,flush=True)

with open('logs/history_results.csv','w',newline='') as fh:
    w=csv.DictWriter(fh,fieldnames=list(rows[0])); w.writeheader(); w.writerows(rows)
cc=run(['gcc','--version'])[1].splitlines()[0]
md=['# History re-verification','',f'Generated by `tools/verify_all.py` with {cc} on {os.uname().sysname} {os.uname().machine}.',
    f'TREE(1)/TREE(2) are computed under AddressSanitizer + UBSan (leak detection off: the golfed code never frees memory by design); TREE(3) is run for {T3}s (a timeout means it is still searching, which is expected).','',
    '## C versions','','| File | Chars | gcc warnings | Compile s | Binary bytes | TREE(1) | TREE(2) | TREE(3) | Result |','|---|---:|---:|---:|---:|---|---|---|---|']
md+=[f"| [{r['file']}](c/{r['file']}.md) | {r['chars']} | {r['warnings']} | {r['compile_s']} | {r['binary_bytes']} | {r['tree1']} | {r['tree2']} | {r['tree3']} | {r['result']} |" for r in rows]
md+=['','## Python versions','','| File | Bytes | TREE(2) (colours reduced to 2) |','|---|---:|---|']
md+=[f"| {r['file']} | {r['bytes']} | {r['tree2']} |" for r in prow]
p=sum(r['result']=='PASS' for r in rows)
md+=['',f'**C summary: {p}/{len(rows)} versions pass.**']
open('logs/history_results.md','w').write('\n'.join(md)+'\n')
print('C pass',p,'/',len(rows))
